### ISSUE TITLE
Support Configuration files

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/lintnet#20]
lintnet.yaml

```yaml
error_level: info
lint_files:
  - lint_files:
      type: gitignore
      value: |
        lintnet/csv.jsonnet
    data_files:
      type: gitignore
      value: |
        **/*.csv
  - lint_files:
      type: module
      source: github_content>suzuki-shunsuke/lintnet-example//hello.jsonnet#v0.1.0
  - lint_files:
      type: module
      source: github_content>suzuki-shunsuke/lintnet-example#v0.1.0
  - lint_files:
      type: module
      source: github_archive>suzuki-shunsuke/lintnet-example//hello.jsonnet#v0.1.0
  - lint_files:
      type: module
      source: http>https://example.com/v0.1.0/hello.jsonnet
```

**Comment by suzuki-shunsuke** [comment]
```yaml
error_level: info
modules:
  - id: suzuki-shunsuke/lintnet-example
    source: github_content>suzuki-shunsuke/lintnet-example//hello.jsonnet#v0.1.0
  - id: suzuki-shunsuke/lintnet-example-2
    source: github_content>suzuki-shunsuke/lintnet-example-2#v0.1.0
  - id: suzuki-shunsuke/lintnet-example-3
    source: github_archive>suzuki-shunsuke/lintnet-example-3#v0.1.0
  - id: http-example
    source: http>https://example.com/v0.1.0/hello.jsonnet
lint_files:
  - lint_files:
      type: gitignore
      paths: |
        lintnet/csv.jsonnet
    data_files:
      type: gitignore
      paths: |
        **/*.csv
  - lint_files:
      module: suzuki-shunsuke/lintnet-example
  - lint_files:
      module: suzuki-shunsuke/lintnet-example-2
      paths: |
        hello.jsonnet
  - lint_files:
      module: suzuki-shunsuke/lintnet-example-3
      paths: |
        hello.jsonnet
  - lint_files:
      module: http-example
```

**Comment by suzuki-shunsuke** [comment]
```yaml
error_level: info
modules:
  - id: toml
    source: github_content>suzuki-shunsuke/lintnet-example//toml.jsonnet#v0.1.0
  - id: suzuki-shunsuke/lintnet-example-2
    source: github_content>suzuki-shunsuke/lintnet-example-2#v0.1.0
  - id: suzuki-shunsuke/lintnet-example-3
    source: github_archive>suzuki-shunsuke/lintnet-example-3#v0.1.0
  - id: yaml
    source: http>https://example.com/v0.1.0/yaml.jsonnet
lint_files:
  - lint_files:
      type: gitignore
      paths: |
        lintnet/csv.jsonnet
      imports:
        - module: suzuki-shunsuke/lintnet-example-2
          path: util.libsonnet
          import: utils.libsonnet # optional
    data_files:
      type: gitignore
      paths: |
        **/*.csv
  - lint_files:
      module: toml
    data_files:
      type: gitignore
      paths: |
        **/*.toml
  - lint_files:
      module: suzuki-shunsuke/lintnet-example-2
      paths: |
        actions.jsonnet
    data_files:
      type: gitignore
      paths: |
        .github/workflows/*.yml
        .github/workflows/*.yaml
  - lint_files:
      module: suzuki-shunsuke/lintnet-example-3
      paths: |
        lintnet/json.jsonnet
    data_files:
      type: gitignore
      paths: |
        **/*.json
  - lint_files:
      module: yaml
    data_files:
      type: gitignore
      paths: |
        **/*.yaml
```

**Comment by suzuki-shunsuke** [comment]
```yaml
error_level: info
modules:
  - id: toml
    source: github_content>suzuki-shunsuke/lintnet-example//toml.jsonnet#v0.1.0
  - id: suzuki-shunsuke/lintnet-example-2
    source: github_content>suzuki-shunsuke/lintnet-example-2#v0.1.0
  - id: suzuki-shunsuke/lintnet-example-3
    source: github_archive>suzuki-shunsuke/lintnet-example-3#v0.1.0
  - id: yaml
    source: http>https://example.com/v0.1.0/yaml.jsonnet
targets:
  - lint_files:
      search_type: equal
      paths:
        - path: lintnet/csv.jsonnet
      imports:
        - module: suzuki-shunsuke/lintnet-example-2
          path: util.libsonnet
          import: utils.libsonnet # optional
    data_files:
      search_type: regexp
      paths:
        - path: .*/[^/]*\.csv
  - lint_files:
      module: toml
    data_files:
      search_type: glob
      paths:
        - path: "*.toml"
  - lint_files:
      module: suzuki-shunsuke/lintnet-example-2
      search_type: equal
      paths:
        - path: actions.jsonnet
    data_files:
      search_type: glob
      paths:
        - path: .github/workflows/*.yml
        - path: .github/workflows/*.yaml
        - path: .github/workflows/fooyaml
          exclude: true
  - lint_files:
      module: suzuki-shunsuke/lintnet-example-3
      paths:
        - path: lintnet/json.jsonnet
    data_files:
      search_type: glob
      paths:
        - path: "*/*.json"
  - lint_files:
      module: yaml
    data_files:
      search_type: glob
      paths:
        - path: "*/*.yaml"
```
