### ISSUE TITLE
Support setting the output template

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/lintnet#25]
e.g.

```sh
lintnet lint --template foo.md [--template-type html/template]
```

The template is rendered by Go's html/template.

**Comment by suzuki-shunsuke** [comment]
```yaml
outputs:
  - dest: stdout # stdout, stderr, file, github issue
    format: json
    template: foo.jsonnet
  - dest: file
    format: markdown
    path: foo.md
    template: foo.tmpl
```
